# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0003_auto_20170225_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cerveza',
            old_name='cerveza',
            new_name='cerveceria',
        ),
    ]
