# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0004_auto_20170225_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais_de_origen',
            options={'verbose_name': 'Pais_de_Origen', 'verbose_name_plural': 'Paises de Origen'},
        ),
        migrations.AlterField(
            model_name='ceveceria',
            name='ceveceria',
            field=models.CharField(max_length=25),
        ),
    ]
