# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0005_auto_20170225_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='CerverzaVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Cerveza para Venta',
                'verbose_name_plural': 'Cervezas para Venta',
            },
        ),
        migrations.RenameField(
            model_name='cerveza',
            old_name='precio',
            new_name='precio_compra',
        ),
        migrations.AddField(
            model_name='cerverzaventa',
            name='cerveza',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taberna.Cerveza'),
        ),
    ]
