# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0007_auto_20170225_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caracteristica',
            options={'verbose_name': 'Caracteristica', 'verbose_name_plural': 'Caracteristicas'},
        ),
        migrations.AlterModelOptions(
            name='cerverzaventa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pais_de_origen',
            options={'verbose_name': 'Pais de Origen', 'verbose_name_plural': 'Paises de Origen'},
        ),
        migrations.RemoveField(
            model_name='cerverzaventa',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mostrar',
            name='id',
        ),
        migrations.AlterField(
            model_name='cerverzaventa',
            name='cerveza',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='taberna.Cerveza'),
        ),
        migrations.AlterField(
            model_name='mostrar',
            name='cerveza',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='taberna.Cerveza'),
        ),
    ]
