# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0008_auto_20170225_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cerverzaventa',
            name='cerveza',
        ),
        migrations.AddField(
            model_name='cerveza',
            name='precio_venta',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='CerverzaVenta',
        ),
    ]
