# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0009_auto_20170225_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(choices=[('BA', 'Barril'), ('BO', 'Botella')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PresentacionCerveza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(default=0)),
                ('disponible', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='cerveza',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='cerveza',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='cerveza',
            name='precio_venta',
        ),
        migrations.AddField(
            model_name='presentacioncerveza',
            name='cerveza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taberna.Cerveza'),
        ),
        migrations.AddField(
            model_name='presentacioncerveza',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taberna.Presentacion'),
        ),
        migrations.AddField(
            model_name='cerveza',
            name='presentaciones',
            field=models.ManyToManyField(through='taberna.PresentacionCerveza', to='taberna.Presentacion'),
        ),
    ]
